spring.datasource.url=jdbc:tc:postgresql:16:///hunger_connect_test
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

app.jwt.secret=test-secret-key-for-unit-tests-only-not-for-production-use
app.storage.endpoint=http://localhost:9000
app.mail.from=test@test.com
app.frontend.url=http://localhost:5173
